version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.7
    environment:
      POETRY_VIRTUALENVS_CREATE: "false"
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install libmemcached-dev
      - run: sudo pip install --upgrade pip
      - run: sudo pip install poetry
      - run: sudo poetry check
      - run: sudo poetry install
      - run: sudo poetry run python manage.py test
      - setup_remote_docker
      - run: |
          TAG=1.0.$CIRCLE_BUILD_NUM
          docker build -t erlendr/swapi:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push erlendr/swapi:$TAG