version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.8
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
      - run:
          command: |
            make test
