version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install libmemcached-dev
      - run: sudo pip install -r requirements.txt
      - run: make test
